name: Android CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Write Dropbox API key to keystore.properties
        run: echo "${{ secrets.DROPBOX_API_KEY }}" > keystore.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "VERSION_NAME=${TAG}" >> $GITHUB_ENV

          # v1.2.3 -> 10203
          VERSION=${TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          VERSION_CODE=$((MAJOR*10000 + MINOR*100 + PATCH))
          echo "VERSION_CODE=${VERSION_CODE}" >> $GITHUB_ENV
      

      - name: Build with Gradle
        run: ./gradlew assembleRelease -PversionName=${{ env.VERSION_NAME }} -PversionCode=${{ env.VERSION_CODE }}

      - name: Upload Release APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
